# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/intelligent_traffic_light/optimized_intellight/optimized_intellight.srcs/sources_1/bd/intellight_v2/ip/intellight_v2_processing_system7_0_0/intellight_v2_processing_system7_0_0.xci
# IP: The module: 'intellight_v2_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/intelligent_traffic_light/optimized_intellight/optimized_intellight.gen/sources_1/bd/intellight_v2/ip/intellight_v2_processing_system7_0_0/intellight_v2_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'intellight_v2_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: f:/intelligent_traffic_light/optimized_intellight/optimized_intellight.srcs/sources_1/bd/intellight_v2/ip/intellight_v2_processing_system7_0_0/intellight_v2_processing_system7_0_0.xci
# IP: The module: 'intellight_v2_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/intelligent_traffic_light/optimized_intellight/optimized_intellight.gen/sources_1/bd/intellight_v2/ip/intellight_v2_processing_system7_0_0/intellight_v2_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'intellight_v2_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
