# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/intelligent_traffic_light/optimized_intellight_v2/optimized_intellight_v2.srcs/sources_1/bd/intellight_v2/ip/intellight_v2_action_ram_wrapper_0_0/intellight_v2_action_ram_wrapper_0_0.xci
# IP: The module: 'intellight_v2_action_ram_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: D:/intelligent_traffic_light/optimized_intellight_v2/optimized_intellight_v2.srcs/sources_1/bd/action_ram/action_ram.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==action_ram || ORIG_REF_NAME==action_ram} -quiet] -quiet

# IP: D:/intelligent_traffic_light/optimized_intellight_v2/optimized_intellight_v2.srcs/sources_1/bd/action_ram/ip/action_ram_blk_mem_gen_0_0/action_ram_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==action_ram_blk_mem_gen_0_0 || ORIG_REF_NAME==action_ram_blk_mem_gen_0_0} -quiet] -quiet

# IP: D:/intelligent_traffic_light/optimized_intellight_v2/optimized_intellight_v2.srcs/sources_1/bd/action_ram/ip/action_ram_action_ram_0_0/action_ram_action_ram_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==action_ram_action_ram_0_0 || ORIG_REF_NAME==action_ram_action_ram_0_0} -quiet] -quiet

# IP: D:/intelligent_traffic_light/optimized_intellight_v2/optimized_intellight_v2.srcs/sources_1/bd/action_ram/ip/action_ram_action_ram_0_1/action_ram_action_ram_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==action_ram_action_ram_0_1 || ORIG_REF_NAME==action_ram_action_ram_0_1} -quiet] -quiet

# IP: D:/intelligent_traffic_light/optimized_intellight_v2/optimized_intellight_v2.srcs/sources_1/bd/action_ram/ip/action_ram_action_ram_1_0/action_ram_action_ram_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==action_ram_action_ram_1_0 || ORIG_REF_NAME==action_ram_action_ram_1_0} -quiet] -quiet

# IP: D:/intelligent_traffic_light/optimized_intellight_v2/optimized_intellight_v2.srcs/sources_1/bd/action_ram/ip/action_ram_xlconstant_0_0/action_ram_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==action_ram_xlconstant_0_0 || ORIG_REF_NAME==action_ram_xlconstant_0_0} -quiet] -quiet

# IP: D:/intelligent_traffic_light/optimized_intellight_v2/optimized_intellight_v2.srcs/sources_1/bd/action_ram/ip/action_ram_const_1_1bit_0/action_ram_const_1_1bit_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==action_ram_const_1_1bit_0 || ORIG_REF_NAME==action_ram_const_1_1bit_0} -quiet] -quiet

# XDC: d:/intelligent_traffic_light/optimized_intellight_v2/optimized_intellight_v2.gen/sources_1/bd/action_ram/action_ram_ooc.xdc

# IP: D:/intelligent_traffic_light/optimized_intellight_v2/optimized_intellight_v2.srcs/sources_1/bd/intellight_v2/ip/intellight_v2_action_ram_wrapper_0_0/intellight_v2_action_ram_wrapper_0_0.xci
# IP: The module: 'intellight_v2_action_ram_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: D:/intelligent_traffic_light/optimized_intellight_v2/optimized_intellight_v2.srcs/sources_1/bd/action_ram/action_ram.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==action_ram || ORIG_REF_NAME==action_ram} -quiet] -quiet

# IP: D:/intelligent_traffic_light/optimized_intellight_v2/optimized_intellight_v2.srcs/sources_1/bd/action_ram/ip/action_ram_blk_mem_gen_0_0/action_ram_blk_mem_gen_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==action_ram_blk_mem_gen_0_0 || ORIG_REF_NAME==action_ram_blk_mem_gen_0_0} -quiet] -quiet

# IP: D:/intelligent_traffic_light/optimized_intellight_v2/optimized_intellight_v2.srcs/sources_1/bd/action_ram/ip/action_ram_action_ram_0_0/action_ram_action_ram_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==action_ram_action_ram_0_0 || ORIG_REF_NAME==action_ram_action_ram_0_0} -quiet] -quiet

# IP: D:/intelligent_traffic_light/optimized_intellight_v2/optimized_intellight_v2.srcs/sources_1/bd/action_ram/ip/action_ram_action_ram_0_1/action_ram_action_ram_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==action_ram_action_ram_0_1 || ORIG_REF_NAME==action_ram_action_ram_0_1} -quiet] -quiet

# IP: D:/intelligent_traffic_light/optimized_intellight_v2/optimized_intellight_v2.srcs/sources_1/bd/action_ram/ip/action_ram_action_ram_1_0/action_ram_action_ram_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==action_ram_action_ram_1_0 || ORIG_REF_NAME==action_ram_action_ram_1_0} -quiet] -quiet

# IP: D:/intelligent_traffic_light/optimized_intellight_v2/optimized_intellight_v2.srcs/sources_1/bd/action_ram/ip/action_ram_xlconstant_0_0/action_ram_xlconstant_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==action_ram_xlconstant_0_0 || ORIG_REF_NAME==action_ram_xlconstant_0_0} -quiet] -quiet

# IP: D:/intelligent_traffic_light/optimized_intellight_v2/optimized_intellight_v2.srcs/sources_1/bd/action_ram/ip/action_ram_const_1_1bit_0/action_ram_const_1_1bit_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==action_ram_const_1_1bit_0 || ORIG_REF_NAME==action_ram_const_1_1bit_0} -quiet] -quiet

# XDC: d:/intelligent_traffic_light/optimized_intellight_v2/optimized_intellight_v2.gen/sources_1/bd/action_ram/action_ram_ooc.xdc
