# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/intelligent_traffic_light/intellight/PYNQ-Z1_C.xdc

# Block Designs: bd/top_level/top_level.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level || ORIG_REF_NAME==top_level} -quiet] -quiet

# IP: bd/top_level/ip/top_level_processing_system7_0_0/top_level_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_processing_system7_0_0 || ORIG_REF_NAME==top_level_processing_system7_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_xbar_0/top_level_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_xbar_0 || ORIG_REF_NAME==top_level_xbar_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_ps7_0_axi_periph_0/top_level_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_ps7_0_axi_periph_0 || ORIG_REF_NAME==top_level_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_rst_ps7_0_100M_0/top_level_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_rst_ps7_0_100M_0 || ORIG_REF_NAME==top_level_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axi_intc_0_0/top_level_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_axi_intc_0_0 || ORIG_REF_NAME==top_level_axi_intc_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_Intellight_Accelerat_0_0/top_level_Intellight_Accelerat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_Intellight_Accelerat_0_0 || ORIG_REF_NAME==top_level_Intellight_Accelerat_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_auto_pc_0/top_level_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_auto_pc_0 || ORIG_REF_NAME==top_level_auto_pc_0} -quiet] -quiet

# XDC: d:/intelligent_traffic_light/intellight/top_level/top_level.gen/sources_1/bd/top_level/top_level_ooc.xdc
