# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/intelligent_traffic_light/optimized_intellight_v2/optimized_intellight_v2.srcs/sources_1/bd/action_ram/ip/action_ram_blk_mem_gen_0_0/action_ram_blk_mem_gen_0_0.xci
# IP: The module: 'action_ram_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/intelligent_traffic_light/optimized_intellight_v2/optimized_intellight_v2.gen/sources_1/bd/action_ram/ip/action_ram_blk_mem_gen_0_0/action_ram_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'action_ram_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/intelligent_traffic_light/optimized_intellight_v2/optimized_intellight_v2.srcs/sources_1/bd/action_ram/ip/action_ram_blk_mem_gen_0_0/action_ram_blk_mem_gen_0_0.xci
# IP: The module: 'action_ram_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/intelligent_traffic_light/optimized_intellight_v2/optimized_intellight_v2.gen/sources_1/bd/action_ram/ip/action_ram_blk_mem_gen_0_0/action_ram_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'action_ram_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
