# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/intelligent_traffic_light/optimized_intellight/optimized_intellight.srcs/sources_1/bd/intellight/ip/intellight_axi_bram_ctrl_1_0/intellight_axi_bram_ctrl_1_0.xci
# IP: The module: 'intellight_axi_bram_ctrl_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/intelligent_traffic_light/optimized_intellight/optimized_intellight.gen/sources_1/bd/intellight/ip/intellight_axi_bram_ctrl_1_0/intellight_axi_bram_ctrl_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'intellight_axi_bram_ctrl_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: F:/intelligent_traffic_light/optimized_intellight/optimized_intellight.srcs/sources_1/bd/intellight/ip/intellight_axi_bram_ctrl_1_0/intellight_axi_bram_ctrl_1_0.xci
# IP: The module: 'intellight_axi_bram_ctrl_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/intelligent_traffic_light/optimized_intellight/optimized_intellight.gen/sources_1/bd/intellight/ip/intellight_axi_bram_ctrl_1_0/intellight_axi_bram_ctrl_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'intellight_axi_bram_ctrl_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
