webtalk_init -webtalk_dir F:/intelligent_traffic_light/optimized_intellight_v2/optimized_intellight_v2.sim/sim_1/behav/xsim/xsim.dir/PG_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Sep 15 16:39:19 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "58fc418a-2f05-4d43-84b4-27d5970ce887" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b736ff8d4d554f54a680987e5c85f8f1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "54" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.09_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7404_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3880516447 -regid "" -xml F:/intelligent_traffic_light/optimized_intellight_v2/optimized_intellight_v2.sim/sim_1/behav/xsim/xsim.dir/PG_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html F:/intelligent_traffic_light/optimized_intellight_v2/optimized_intellight_v2.sim/sim_1/behav/xsim/xsim.dir/PG_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm F:/intelligent_traffic_light/optimized_intellight_v2/optimized_intellight_v2.sim/sim_1/behav/xsim/xsim.dir/PG_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
