# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/Intelligent Traffic Light/optimized_intellight/optimized_intellight.srcs/sources_1/bd/intellight/ip/intellight_RAM0_1/intellight_RAM0_1.xci
# IP: The module: 'intellight_RAM0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Intelligent Traffic Light/optimized_intellight/optimized_intellight.gen/sources_1/bd/intellight/ip/intellight_RAM0_1/intellight_RAM0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'intellight_RAM0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: F:/Intelligent Traffic Light/optimized_intellight/optimized_intellight.srcs/sources_1/bd/intellight/ip/intellight_RAM0_1/intellight_RAM0_1.xci
# IP: The module: 'intellight_RAM0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Intelligent Traffic Light/optimized_intellight/optimized_intellight.gen/sources_1/bd/intellight/ip/intellight_RAM0_1/intellight_RAM0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'intellight_RAM0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
