# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: F:/intelligent_traffic_light/optimized_intellight/board_file/PYNQ-Z1_C.xdc

# Block Designs: bd/intellight_v2/intellight_v2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2 || ORIG_REF_NAME==intellight_v2} -quiet] -quiet

# IP: bd/intellight_v2/ip/intellight_v2_const_1_0/intellight_v2_const_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2_const_1_0 || ORIG_REF_NAME==intellight_v2_const_1_0} -quiet] -quiet

# IP: bd/intellight_v2/ip/intellight_v2_cons_0000_0/intellight_v2_cons_0000_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2_cons_0000_0 || ORIG_REF_NAME==intellight_v2_cons_0000_0} -quiet] -quiet

# IP: bd/intellight_v2/ip/intellight_v2_Action_RAM0_0/intellight_v2_Action_RAM0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2_Action_RAM0_0 || ORIG_REF_NAME==intellight_v2_Action_RAM0_0} -quiet] -quiet

# IP: bd/intellight_v2/ip/intellight_v2_Action_RAM1_0/intellight_v2_Action_RAM1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2_Action_RAM1_0 || ORIG_REF_NAME==intellight_v2_Action_RAM1_0} -quiet] -quiet

# IP: bd/intellight_v2/ip/intellight_v2_Action_RAM2_0/intellight_v2_Action_RAM2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2_Action_RAM2_0 || ORIG_REF_NAME==intellight_v2_Action_RAM2_0} -quiet] -quiet

# IP: bd/intellight_v2/ip/intellight_v2_Action_RAM3_0/intellight_v2_Action_RAM3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2_Action_RAM3_0 || ORIG_REF_NAME==intellight_v2_Action_RAM3_0} -quiet] -quiet

# IP: bd/intellight_v2/ip/intellight_v2_CU_0_0/intellight_v2_CU_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2_CU_0_0 || ORIG_REF_NAME==intellight_v2_CU_0_0} -quiet] -quiet

# IP: bd/intellight_v2/ip/intellight_v2_MII_0_0/intellight_v2_MII_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2_MII_0_0 || ORIG_REF_NAME==intellight_v2_MII_0_0} -quiet] -quiet

# IP: bd/intellight_v2/ip/intellight_v2_PG_0_0/intellight_v2_PG_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2_PG_0_0 || ORIG_REF_NAME==intellight_v2_PG_0_0} -quiet] -quiet

# IP: bd/intellight_v2/ip/intellight_v2_QA_0_0/intellight_v2_QA_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2_QA_0_0 || ORIG_REF_NAME==intellight_v2_QA_0_0} -quiet] -quiet

# IP: bd/intellight_v2/ip/intellight_v2_RD_0_0/intellight_v2_RD_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2_RD_0_0 || ORIG_REF_NAME==intellight_v2_RD_0_0} -quiet] -quiet

# IP: bd/intellight_v2/ip/intellight_v2_SD_0_0/intellight_v2_SD_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2_SD_0_0 || ORIG_REF_NAME==intellight_v2_SD_0_0} -quiet] -quiet

# IP: bd/intellight_v2/ip/intellight_v2_axi_intc_0_0/intellight_v2_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2_axi_intc_0_0 || ORIG_REF_NAME==intellight_v2_axi_intc_0_0} -quiet] -quiet

# IP: bd/intellight_v2/ip/intellight_v2_axi_smc_0/intellight_v2_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2_axi_smc_0 || ORIG_REF_NAME==intellight_v2_axi_smc_0} -quiet] -quiet

# IP: bd/intellight_v2/ip/intellight_v2_intellight_0_0/intellight_v2_intellight_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2_intellight_0_0 || ORIG_REF_NAME==intellight_v2_intellight_0_0} -quiet] -quiet

# IP: bd/intellight_v2/ip/intellight_v2_processing_system7_0_0/intellight_v2_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2_processing_system7_0_0 || ORIG_REF_NAME==intellight_v2_processing_system7_0_0} -quiet] -quiet

# IP: bd/intellight_v2/ip/intellight_v2_rst_clk_100M_0/intellight_v2_rst_clk_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2_rst_clk_100M_0 || ORIG_REF_NAME==intellight_v2_rst_clk_100M_0} -quiet] -quiet

# XDC: f:/intelligent_traffic_light/optimized_intellight/optimized_intellight.gen/sources_1/bd/intellight_v2/intellight_v2_ooc.xdc
