# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/intelligent_traffic_light/intellight/prototype/prototype.srcs/sources_1/bd/Intellight/ip/Intellight_processing_system7_0_0/Intellight_processing_system7_0_0.xci
# IP: The module: 'Intellight_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/intelligent_traffic_light/intellight/prototype/prototype.gen/sources_1/bd/Intellight/ip/Intellight_processing_system7_0_0/Intellight_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Intellight_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/intelligent_traffic_light/intellight/prototype/prototype.srcs/sources_1/bd/Intellight/ip/Intellight_processing_system7_0_0/Intellight_processing_system7_0_0.xci
# IP: The module: 'Intellight_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/intelligent_traffic_light/intellight/prototype/prototype.gen/sources_1/bd/Intellight/ip/Intellight_processing_system7_0_0/Intellight_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Intellight_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
