# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/intelligent_traffic_light/optimized_intellight_v2/board_file/PYNQ-Z1_C.xdc

# Block Designs: bd/action_ram/action_ram.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==action_ram || ORIG_REF_NAME==action_ram} -quiet] -quiet

# IP: bd/action_ram/ip/action_ram_blk_mem_gen_0_0/action_ram_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==action_ram_blk_mem_gen_0_0 || ORIG_REF_NAME==action_ram_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/action_ram/ip/action_ram_action_ram_0_0/action_ram_action_ram_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==action_ram_action_ram_0_0 || ORIG_REF_NAME==action_ram_action_ram_0_0} -quiet] -quiet

# IP: bd/action_ram/ip/action_ram_action_ram_0_1/action_ram_action_ram_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==action_ram_action_ram_0_1 || ORIG_REF_NAME==action_ram_action_ram_0_1} -quiet] -quiet

# IP: bd/action_ram/ip/action_ram_action_ram_1_0/action_ram_action_ram_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==action_ram_action_ram_1_0 || ORIG_REF_NAME==action_ram_action_ram_1_0} -quiet] -quiet

# IP: bd/action_ram/ip/action_ram_xlconstant_0_0/action_ram_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==action_ram_xlconstant_0_0 || ORIG_REF_NAME==action_ram_xlconstant_0_0} -quiet] -quiet

# IP: bd/action_ram/ip/action_ram_const_1_1bit_0/action_ram_const_1_1bit_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==action_ram_const_1_1bit_0 || ORIG_REF_NAME==action_ram_const_1_1bit_0} -quiet] -quiet

# Block Designs: bd/intellight_v2/intellight_v2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2 || ORIG_REF_NAME==intellight_v2} -quiet] -quiet

# IP: bd/intellight_v2/ip/intellight_v2_processing_system7_0_1/intellight_v2_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2_processing_system7_0_1 || ORIG_REF_NAME==intellight_v2_processing_system7_0_1} -quiet] -quiet

# IP: bd/intellight_v2/ip/intellight_v2_rst_ps7_0_100M_0/intellight_v2_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2_rst_ps7_0_100M_0 || ORIG_REF_NAME==intellight_v2_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/intellight_v2/ip/intellight_v2_SD_0_1/intellight_v2_SD_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2_SD_0_1 || ORIG_REF_NAME==intellight_v2_SD_0_1} -quiet] -quiet

# IP: bd/intellight_v2/ip/intellight_v2_axi_intc_0_0/intellight_v2_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2_axi_intc_0_0 || ORIG_REF_NAME==intellight_v2_axi_intc_0_0} -quiet] -quiet

# IP: bd/intellight_v2/ip/intellight_v2_xbar_0/intellight_v2_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2_xbar_0 || ORIG_REF_NAME==intellight_v2_xbar_0} -quiet] -quiet

# IP: bd/intellight_v2/ip/intellight_v2_ps7_0_axi_periph_1/intellight_v2_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2_ps7_0_axi_periph_1 || ORIG_REF_NAME==intellight_v2_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/intellight_v2/ip/intellight_v2_RD_0_0/intellight_v2_RD_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2_RD_0_0 || ORIG_REF_NAME==intellight_v2_RD_0_0} -quiet] -quiet

# IP: bd/intellight_v2/ip/intellight_v2_CU_0_0/intellight_v2_CU_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2_CU_0_0 || ORIG_REF_NAME==intellight_v2_CU_0_0} -quiet] -quiet

# IP: bd/intellight_v2/ip/intellight_v2_QA_0_0/intellight_v2_QA_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2_QA_0_0 || ORIG_REF_NAME==intellight_v2_QA_0_0} -quiet] -quiet

# IP: bd/intellight_v2/ip/intellight_v2_PG_0_0/intellight_v2_PG_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2_PG_0_0 || ORIG_REF_NAME==intellight_v2_PG_0_0} -quiet] -quiet

# IP: bd/intellight_v2/ip/intellight_v2_MOI_0_0/intellight_v2_MOI_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2_MOI_0_0 || ORIG_REF_NAME==intellight_v2_MOI_0_0} -quiet] -quiet

# IP: bd/intellight_v2/ip/intellight_v2_action_ram_wrapper_0_0/intellight_v2_action_ram_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2_action_ram_wrapper_0_0 || ORIG_REF_NAME==intellight_v2_action_ram_wrapper_0_0} -quiet] -quiet

# Block Designs: bd/action_ram/action_ram.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==action_ram || ORIG_REF_NAME==action_ram} -quiet] -quiet

# IP: bd/action_ram/ip/action_ram_blk_mem_gen_0_0/action_ram_blk_mem_gen_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==action_ram_blk_mem_gen_0_0 || ORIG_REF_NAME==action_ram_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/action_ram/ip/action_ram_action_ram_0_0/action_ram_action_ram_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==action_ram_action_ram_0_0 || ORIG_REF_NAME==action_ram_action_ram_0_0} -quiet] -quiet

# IP: bd/action_ram/ip/action_ram_action_ram_0_1/action_ram_action_ram_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==action_ram_action_ram_0_1 || ORIG_REF_NAME==action_ram_action_ram_0_1} -quiet] -quiet

# IP: bd/action_ram/ip/action_ram_action_ram_1_0/action_ram_action_ram_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==action_ram_action_ram_1_0 || ORIG_REF_NAME==action_ram_action_ram_1_0} -quiet] -quiet

# IP: bd/action_ram/ip/action_ram_xlconstant_0_0/action_ram_xlconstant_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==action_ram_xlconstant_0_0 || ORIG_REF_NAME==action_ram_xlconstant_0_0} -quiet] -quiet

# IP: bd/action_ram/ip/action_ram_const_1_1bit_0/action_ram_const_1_1bit_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==action_ram_const_1_1bit_0 || ORIG_REF_NAME==action_ram_const_1_1bit_0} -quiet] -quiet

# IP: bd/intellight_v2/ip/intellight_v2_MII_0_0/intellight_v2_MII_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2_MII_0_0 || ORIG_REF_NAME==intellight_v2_MII_0_0} -quiet] -quiet

# IP: bd/intellight_v2/ip/intellight_v2_intellight_database_0_0/intellight_v2_intellight_database_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2_intellight_database_0_0 || ORIG_REF_NAME==intellight_v2_intellight_database_0_0} -quiet] -quiet

# IP: bd/intellight_v2/ip/intellight_v2_auto_pc_0/intellight_v2_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_v2_auto_pc_0 || ORIG_REF_NAME==intellight_v2_auto_pc_0} -quiet] -quiet

# XDC: d:/intelligent_traffic_light/optimized_intellight_v2/optimized_intellight_v2.gen/sources_1/bd/action_ram/action_ram_ooc.xdc

# XDC: d:/intelligent_traffic_light/optimized_intellight_v2/optimized_intellight_v2.gen/sources_1/bd/action_ram/action_ram_ooc.xdc

# XDC: d:/intelligent_traffic_light/optimized_intellight_v2/optimized_intellight_v2.gen/sources_1/bd/intellight_v2/intellight_v2_ooc.xdc
