# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: F:/intelligent_traffic_light/optimized_intellight/board_file/PYNQ-Z1_C.xdc

# Block Designs: bd/intellight/intellight.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight || ORIG_REF_NAME==intellight} -quiet] -quiet

# IP: bd/intellight/ip/intellight_xlconstant_0_1/intellight_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_xlconstant_0_1 || ORIG_REF_NAME==intellight_xlconstant_0_1} -quiet] -quiet

# IP: bd/intellight/ip/intellight_xlconstant_0_0/intellight_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_xlconstant_0_0 || ORIG_REF_NAME==intellight_xlconstant_0_0} -quiet] -quiet

# IP: bd/intellight/ip/intellight_blk_mem_gen_0_0/intellight_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_blk_mem_gen_0_0 || ORIG_REF_NAME==intellight_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/intellight/ip/intellight_RAM0_0/intellight_RAM0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_RAM0_0 || ORIG_REF_NAME==intellight_RAM0_0} -quiet] -quiet

# IP: bd/intellight/ip/intellight_RAM1_0/intellight_RAM1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_RAM1_0 || ORIG_REF_NAME==intellight_RAM1_0} -quiet] -quiet

# IP: bd/intellight/ip/intellight_RAM2_0/intellight_RAM2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_RAM2_0 || ORIG_REF_NAME==intellight_RAM2_0} -quiet] -quiet

# IP: bd/intellight/ip/intellight_const_1_0/intellight_const_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_const_1_0 || ORIG_REF_NAME==intellight_const_1_0} -quiet] -quiet

# IP: bd/intellight/ip/intellight_RAM0_1/intellight_RAM0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_RAM0_1 || ORIG_REF_NAME==intellight_RAM0_1} -quiet] -quiet

# IP: bd/intellight/ip/intellight_RAM1_1/intellight_RAM1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_RAM1_1 || ORIG_REF_NAME==intellight_RAM1_1} -quiet] -quiet

# IP: bd/intellight/ip/intellight_RAM2_1/intellight_RAM2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_RAM2_1 || ORIG_REF_NAME==intellight_RAM2_1} -quiet] -quiet

# IP: bd/intellight/ip/intellight_RAM3_0/intellight_RAM3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_RAM3_0 || ORIG_REF_NAME==intellight_RAM3_0} -quiet] -quiet

# IP: bd/intellight/ip/intellight_axi_bram_ctrl_1_0/intellight_axi_bram_ctrl_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_axi_bram_ctrl_1_0 || ORIG_REF_NAME==intellight_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/intellight/ip/intellight_axi_bram_ctrl_1_1/intellight_axi_bram_ctrl_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_axi_bram_ctrl_1_1 || ORIG_REF_NAME==intellight_axi_bram_ctrl_1_1} -quiet] -quiet

# IP: bd/intellight/ip/intellight_axi_bram_ctrl_2_0/intellight_axi_bram_ctrl_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_axi_bram_ctrl_2_0 || ORIG_REF_NAME==intellight_axi_bram_ctrl_2_0} -quiet] -quiet

# IP: bd/intellight/ip/intellight_axi_bram_ctrl_0_0/intellight_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_axi_bram_ctrl_0_0 || ORIG_REF_NAME==intellight_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/intellight/ip/intellight_processing_system7_0_0/intellight_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_processing_system7_0_0 || ORIG_REF_NAME==intellight_processing_system7_0_0} -quiet] -quiet

# IP: bd/intellight/ip/intellight_axi_smc_0/intellight_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_axi_smc_0 || ORIG_REF_NAME==intellight_axi_smc_0} -quiet] -quiet

# IP: bd/intellight/ip/intellight_rst_clk_100M_0/intellight_rst_clk_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_rst_clk_100M_0 || ORIG_REF_NAME==intellight_rst_clk_100M_0} -quiet] -quiet

# IP: bd/intellight/ip/intellight_axi_intc_0_0/intellight_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_axi_intc_0_0 || ORIG_REF_NAME==intellight_axi_intc_0_0} -quiet] -quiet

# IP: bd/intellight/ip/intellight_RD_0_0/intellight_RD_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_RD_0_0 || ORIG_REF_NAME==intellight_RD_0_0} -quiet] -quiet

# IP: bd/intellight/ip/intellight_PG_0_0/intellight_PG_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_PG_0_0 || ORIG_REF_NAME==intellight_PG_0_0} -quiet] -quiet

# IP: bd/intellight/ip/intellight_QA_0_0/intellight_QA_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_QA_0_0 || ORIG_REF_NAME==intellight_QA_0_0} -quiet] -quiet

# IP: bd/intellight/ip/intellight_intellight_0_0/intellight_intellight_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_intellight_0_0 || ORIG_REF_NAME==intellight_intellight_0_0} -quiet] -quiet

# IP: bd/intellight/ip/intellight_SD_0_0/intellight_SD_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_SD_0_0 || ORIG_REF_NAME==intellight_SD_0_0} -quiet] -quiet

# IP: bd/intellight/ip/intellight_MII_0_0/intellight_MII_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_MII_0_0 || ORIG_REF_NAME==intellight_MII_0_0} -quiet] -quiet

# IP: bd/intellight/ip/intellight_CU_0_0/intellight_CU_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intellight_CU_0_0 || ORIG_REF_NAME==intellight_CU_0_0} -quiet] -quiet

# XDC: f:/intelligent_traffic_light/optimized_intellight/optimized_intellight.gen/sources_1/bd/intellight/intellight_ooc.xdc
