# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/intelligent_traffic_light/intellight/top_level/top_level.gen/sources_1/bd/top_level/bd/Q_Matrix_AXI_inst_0/ip/Q_Matrix_AXI_inst_0_axi_aram_ctrl_3_0/Q_Matrix_AXI_inst_0_axi_aram_ctrl_3_0.xci
# IP: The module: 'Q_Matrix_AXI_inst_0_axi_aram_ctrl_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/intelligent_traffic_light/intellight/top_level/top_level.gen/sources_1/bd/top_level/bd/Q_Matrix_AXI_inst_0/ip/Q_Matrix_AXI_inst_0_axi_aram_ctrl_3_0/Q_Matrix_AXI_inst_0_axi_aram_ctrl_3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Q_Matrix_AXI_inst_0_axi_aram_ctrl_3_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/intelligent_traffic_light/intellight/top_level/top_level.gen/sources_1/bd/top_level/bd/Q_Matrix_AXI_inst_0/ip/Q_Matrix_AXI_inst_0_axi_aram_ctrl_3_0/Q_Matrix_AXI_inst_0_axi_aram_ctrl_3_0.xci
# IP: The module: 'Q_Matrix_AXI_inst_0_axi_aram_ctrl_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/intelligent_traffic_light/intellight/top_level/top_level.gen/sources_1/bd/top_level/bd/Q_Matrix_AXI_inst_0/ip/Q_Matrix_AXI_inst_0_axi_aram_ctrl_3_0/Q_Matrix_AXI_inst_0_axi_aram_ctrl_3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Q_Matrix_AXI_inst_0_axi_aram_ctrl_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
