# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/top_level/PYNQ-Z1_C.xdc

# Block Designs: bd/Intellight/Intellight.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Intellight || ORIG_REF_NAME==Intellight} -quiet] -quiet

# IP: bd/Intellight/ip/Intellight_action_ram_0_0/Intellight_action_ram_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Intellight_action_ram_0_0 || ORIG_REF_NAME==Intellight_action_ram_0_0} -quiet] -quiet

# IP: bd/Intellight/ip/Intellight_action_ram_1_0/Intellight_action_ram_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Intellight_action_ram_1_0 || ORIG_REF_NAME==Intellight_action_ram_1_0} -quiet] -quiet

# IP: bd/Intellight/ip/Intellight_action_ram_2_0/Intellight_action_ram_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Intellight_action_ram_2_0 || ORIG_REF_NAME==Intellight_action_ram_2_0} -quiet] -quiet

# IP: bd/Intellight/ip/Intellight_action_ram_3_0/Intellight_action_ram_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Intellight_action_ram_3_0 || ORIG_REF_NAME==Intellight_action_ram_3_0} -quiet] -quiet

# IP: bd/Intellight/ip/Intellight_const_1_1bit_0/Intellight_const_1_1bit_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Intellight_const_1_1bit_0 || ORIG_REF_NAME==Intellight_const_1_1bit_0} -quiet] -quiet

# IP: bd/Intellight/ip/Intellight_const_0_8bit_0/Intellight_const_0_8bit_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Intellight_const_0_8bit_0 || ORIG_REF_NAME==Intellight_const_0_8bit_0} -quiet] -quiet

# IP: bd/Intellight/ip/Intellight_Accelerator_0_0/Intellight_Accelerator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Intellight_Accelerator_0_0 || ORIG_REF_NAME==Intellight_Accelerator_0_0} -quiet] -quiet

# IP: bd/Intellight/ip/Intellight_axi_intc_0_0/Intellight_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Intellight_axi_intc_0_0 || ORIG_REF_NAME==Intellight_axi_intc_0_0} -quiet] -quiet

# IP: bd/Intellight/ip/Intellight_database_0_0/Intellight_database_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Intellight_database_0_0 || ORIG_REF_NAME==Intellight_database_0_0} -quiet] -quiet

# IP: bd/Intellight/ip/Intellight_processing_system7_0_0/Intellight_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Intellight_processing_system7_0_0 || ORIG_REF_NAME==Intellight_processing_system7_0_0} -quiet] -quiet

# IP: bd/Intellight/ip/Intellight_xbar_0/Intellight_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Intellight_xbar_0 || ORIG_REF_NAME==Intellight_xbar_0} -quiet] -quiet

# IP: bd/Intellight/ip/Intellight_ps7_0_axi_periph_0/Intellight_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Intellight_ps7_0_axi_periph_0 || ORIG_REF_NAME==Intellight_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Intellight/ip/Intellight_rst_ps7_0_100M_0/Intellight_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Intellight_rst_ps7_0_100M_0 || ORIG_REF_NAME==Intellight_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Intellight/ip/Intellight_action_ram_0_1/Intellight_action_ram_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Intellight_action_ram_0_1 || ORIG_REF_NAME==Intellight_action_ram_0_1} -quiet] -quiet

# IP: bd/Intellight/ip/Intellight_action_ram_1_1/Intellight_action_ram_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Intellight_action_ram_1_1 || ORIG_REF_NAME==Intellight_action_ram_1_1} -quiet] -quiet

# IP: bd/Intellight/ip/Intellight_action_ram_2_1/Intellight_action_ram_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Intellight_action_ram_2_1 || ORIG_REF_NAME==Intellight_action_ram_2_1} -quiet] -quiet

# IP: bd/Intellight/ip/Intellight_action_ram_3_1/Intellight_action_ram_3_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Intellight_action_ram_3_1 || ORIG_REF_NAME==Intellight_action_ram_3_1} -quiet] -quiet

# IP: bd/Intellight/ip/Intellight_axi_aram_ctrl_0_0/Intellight_axi_aram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Intellight_axi_aram_ctrl_0_0 || ORIG_REF_NAME==Intellight_axi_aram_ctrl_0_0} -quiet] -quiet

# IP: bd/Intellight/ip/Intellight_axi_aram_ctrl_1_0/Intellight_axi_aram_ctrl_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Intellight_axi_aram_ctrl_1_0 || ORIG_REF_NAME==Intellight_axi_aram_ctrl_1_0} -quiet] -quiet

# IP: bd/Intellight/ip/Intellight_axi_aram_ctrl_2_0/Intellight_axi_aram_ctrl_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Intellight_axi_aram_ctrl_2_0 || ORIG_REF_NAME==Intellight_axi_aram_ctrl_2_0} -quiet] -quiet

# IP: bd/Intellight/ip/Intellight_axi_aram_ctrl_3_0/Intellight_axi_aram_ctrl_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Intellight_axi_aram_ctrl_3_0 || ORIG_REF_NAME==Intellight_axi_aram_ctrl_3_0} -quiet] -quiet

# IP: bd/Intellight/ip/Intellight_auto_pc_2/Intellight_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Intellight_auto_pc_2 || ORIG_REF_NAME==Intellight_auto_pc_2} -quiet] -quiet

# IP: bd/Intellight/ip/Intellight_auto_us_0/Intellight_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Intellight_auto_us_0 || ORIG_REF_NAME==Intellight_auto_us_0} -quiet] -quiet

# IP: bd/Intellight/ip/Intellight_auto_ds_0/Intellight_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Intellight_auto_ds_0 || ORIG_REF_NAME==Intellight_auto_ds_0} -quiet] -quiet

# IP: bd/Intellight/ip/Intellight_auto_pc_0/Intellight_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Intellight_auto_pc_0 || ORIG_REF_NAME==Intellight_auto_pc_0} -quiet] -quiet

# IP: bd/Intellight/ip/Intellight_auto_ds_1/Intellight_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Intellight_auto_ds_1 || ORIG_REF_NAME==Intellight_auto_ds_1} -quiet] -quiet

# IP: bd/Intellight/ip/Intellight_auto_pc_1/Intellight_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Intellight_auto_pc_1 || ORIG_REF_NAME==Intellight_auto_pc_1} -quiet] -quiet

# XDC: d:/intelligent_traffic_light/intellight/prototype/prototype.gen/sources_1/bd/Intellight/Intellight_ooc.xdc
