# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/riset/optimized_intellight/optimized_intellight.srcs/sources_1/bd/intellight/ip/intellight_RAM2_0/intellight_RAM2_0.xci
# IP: The module: 'intellight_RAM2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/riset/optimized_intellight/optimized_intellight.gen/sources_1/bd/intellight/ip/intellight_RAM2_0/intellight_RAM2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'intellight_RAM2_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: f:/riset/optimized_intellight/optimized_intellight.srcs/sources_1/bd/intellight/ip/intellight_RAM2_0/intellight_RAM2_0.xci
# IP: The module: 'intellight_RAM2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/riset/optimized_intellight/optimized_intellight.gen/sources_1/bd/intellight/ip/intellight_RAM2_0/intellight_RAM2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'intellight_RAM2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
