@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Aug 18 05:37:05 +0700 2022
REM SW Build 3247384 on Thu Jun 10 19:36:33 MDT 2021
REM
REM IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim simulate_tb_time_synth -key {Post-Synthesis:sim_1:Timing:simulate_tb} -tclbatch simulate_tb.tcl -protoinst "protoinst_files/simulate.protoinst" -protoinst "protoinst_files/bd_0108.protoinst" -log simulate.log"
call xsim  simulate_tb_time_synth -key {Post-Synthesis:sim_1:Timing:simulate_tb} -tclbatch simulate_tb.tcl -protoinst "protoinst_files/simulate.protoinst" -protoinst "protoinst_files/bd_0108.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
